### ISSUE TITLE
factor retention methods

### ISSUE THREAD

**Issue by mdsteiner** [mdsteiner/EFAtools#15]

**Comment by mdsteiner** [comment]
To implement:
- From Auerswald (code at https://osf.io/gqma2/?view_only=d03efba1fd0f4c849a87db82e6705668):
	- Kaiser-Guttman Criterion (KGC)
		- with PCA eigenvalues
		- with EFA eigenvalues
	- Comparison Data (CD), see also Ruscio and Roche (2012)
	- Empirical Kaiser Criterion (EKC) by Braeken & van Assen, 2017
	- Sequential chisq model test (SMT)
- Goretzko and Bühner 2020:
	- ML model


Check literature: Revised PA by Green et al 2012 for eigenvalues of EFA and 95th percentile as reference eigenvalue

**Comment by sgrieder** [comment]
Write function FACRET (o.ä.) that incorporates all factor retention methods and does a KMO and Bartlett test at the beginning

**Comment by sgrieder** [comment]
Update PARALLEL:
- Check literature: Revised PA by Green et al 2012 for eigenvalues of EFA and 95th percentile as reference eigenvalue
- Rename eigen_type arguments: "PCA", "SMC", "EFA"

**Comment by sgrieder** [comment]
In all functions: rename ctrl in settings

**Comment by sgrieder** [comment]
On deviance vs. chi square for AIC:
- https://online.stat.psu.edu/stat504/node/60/

**Comment by sgrieder** [comment]
Implement functions such that all methods can be selected at once:
- CD? (pearson, spearman, kendall -> depends on data, right?)
- HULL? (for estimation method PAF, ULS, ML)
- KGC -> PCA, SMC and EFA
- PARALLEL -> PCA, SMC, EFA
- SMT? (also allow to deselect certain aspects? currently all are done always)
