### ISSUE TITLE
rotation methods

### ISSUE THREAD

**Issue by mdsteiner** [mdsteiner/EFAtools#17]
implement additional rotation methods

**Comment by sgrieder** [comment]
These are all rotations from GPArotation used in psych::fa(). In bold are rotations used in SPSS (only these + varimax and promax are available there).

_**Oblique:**_

**Oblimin**
Quartimin
(Simplimax) -> needs additional argument k
BentlerQ
GeominQ
Biquartimin (= bifactor orthogonal)

_**Orthogonal:**_

**Quartimax**
BentlerT
**Equamax**
GeominT
Bifactor

**Comment by sgrieder** [comment]
add new oblique rotations in SL check

**Comment by sgrieder** [comment]
use a default precision (also for varimax)

**Comment by sgrieder** [comment]
match.arg for order_type? what are possibilities there?

**Comment by sgrieder** [comment]
why in fac rotation matrix from GPArotation is again processed to get another rotation matrix?

**Comment by sgrieder** [comment]
fehler in psych package: argument kappa not entered in equamax function, so it does a quartimax. And stop message should be "equamax", not "biquartimin"

**Comment by sgrieder** [comment]
use match.arg for rotation methods? or just leave it open so more can be used with GPArotation package? (dangerous, because not all work with GPAort or GPAoblq)

**Comment by sgrieder** [comment]
maybe change default for kaiser to FALSE (FALSE everywhere in GPArotation)

**Comment by sgrieder** [comment]
check if Phi is really covariance matrix and not correlation matrix

**Comment by sgrieder** [comment]
> use a default precision (also for varimax)
