### ISSUE TITLE
Debug PAF

### ISSUE THREAD

**Issue by sgrieder** [mdsteiner/EFAtools#28]
EFA(IDS2_R, n_factors = 5, N = 1991, type = "none", method = "PAF",
    rotation = "none", max_iter = 500, init_comm = "mac",
    criterion = 1e4, criterion_type = "sums", abs_eigen = FALSE)

This throws an error (cannot find dimnames). No problems if type is specified, error persists with
init_com = "smc" or "unity" or with abs_eign = TRUE.

**Comment by mdsteiner** [comment]
the problem was the `criterion = 1e4` instead of `criterion = 1e-4`.
