### ISSUE TITLE
perform examples with testmodels

### ISSUE THREAD

**Issue by mdsteiner** [mdsteiner/EFAtools#32]

**Comment by sgrieder** [comment]
To do for:

BARTLETT.R
compare.R
DOSPERT_doc.R
EFA.R
EFAtools-package.R
helper.R
HULL.R
IDS2_R_doc.R
KGC.R
KMO.R
ML.R
OMEGA_helper.R
OMEGA.R
PAF.R
PARALLEL.R
plot.HULL.R
plot.KGC.R
plot.PARALLEL.R
population_models_doc.R
print.BARTLETT.R
print.COMPARE.R
print.EFA.R
print.HULL.R
print.KGC.R
print.KMO.R
print.LOADINGS.R
print.OMEGA.R
print.PARALLEL.R
print.SL.R
print.SLLOADINGS.R
PROMAX.R
RcppExports.R
RiskDimensions_doc.R
ROTATE_OBLQ.R
ROTATE_ORTH.R
SL.R
SPSS_doc.R
test_models_doc.R
ULS.R
utils-pipe.R
VARIMAX_SPSS.R
VARIMAX.R
WJIV_ages_3_5_doc.R
WJIV_ages_6_8_doc.R
WJIV_ages_9_13_doc.R
WJIV_ages_14_19_doc.R
WJIV_ages_20_39_doc.R
WJIV_ages_40_90_doc.R
