### ISSUE TITLE
fancy up prints with cli

### ISSUE THREAD

**Issue by mdsteiner** [mdsteiner/EFAtools#45]
e.g., add spinners while fitting

**Comment by sgrieder** [comment]
The following could be interesting:
- rules in print function

**Comment by sgrieder** [comment]
https://cli.r-lib.org/articles/semantic-cli.html

**Comment by sgrieder** [comment]
Print functions to update:

- print.BARTLETT.R
- print.CD.R
- print.COMPARE.R
- print.EFA.R
- print.EKC.R
- print.HULL.R
- print.KGC.R
- print.KMO.R
- print.LOADINGS.R
- print.N_FACTORS.R
- print.OMEGA.R
- print.PARALLEL.R
- print.SL.R
- print.SLLOADINGS.R
- print.SMT.R

**Comment by sgrieder** [comment]
Functions to implement spinners:
- HULL
- PARALLEL
- CD
- evtl. SMT?

**Comment by sgrieder** [comment]
Messages, errors and warnings -> use cli functions
