### ISSUE TITLE
test all functions!

### ISSUE THREAD

**Issue by sgrieder** [mdsteiner/EFAtools#49]
rerun all tests at the very end

**Comment by sgrieder** [comment]
use testthat for this...

**Comment by mdsteiner** [comment]
- BARTLETT.R
- CD.R
- compare.R
- EFA.R
- EKC.R
- helper.R
- HULL.R
- KGC.R
- KMO.R
- N_FACTORS.R
- OMEGA.R
- PARALLEL.R
- SL.R
- SMT.R

**Comment by sgrieder** [comment]
also check settings! (see, e.g., test-BARTLETT)

**Comment by sgrieder** [comment]
rerun all tests at the very end

**Comment by sgrieder** [comment]
within all functions, test that x is a matrix or dataframe

**Comment by sgrieder** [comment]
EKC no test for singular matrix, correct? KGC has it..

**Comment by sgrieder** [comment]
See that errors and warnings are all the same in all functions where the input for x is the same

**Comment by sgrieder** [comment]
error in PARALLEL: '"N" was not set and could not be taken from data. Please specify N and try again.'
Do we need this error everywhere?

**Comment by sgrieder** [comment]
How can we test for the message (x was not a correlation matrx...) if it is not a message?

**Comment by sgrieder** [comment]
add "silent = TRUE" everywhere where solve(R) is tried

**Comment by sgrieder** [comment]
Function reference for testthat:
https://testthat.r-lib.org/reference/index.html

**Comment by sgrieder** [comment]
SMT:
- What to do if no chi-square value becomes significant? Set nfac_chi to 0 or to NA?
- Test RMSEA and AIC? How? Just same as p-values?

**Comment by sgrieder** [comment]
Floor doesn't always work... if there are only four variables, 2 factors result in negative degrees of freedom (-1) --> underindentified model

Solved like this: if n_vars 4 or less -> max_factor  = 1; else: floor(n_vars / 2)

**Comment by sgrieder** [comment]
Is RMSEA calculated correctly?

**Comment by sgrieder** [comment]
Test correctness of loadings with population model

**Comment by sgrieder** [comment]
For EFA functions:
- Do not test communalities
- Test variances accounted for and gof in helper functions, test only that right fit indices are returned (CAF and df for PAF, all for ML and ULS)

**Comment by sgrieder** [comment]
Check that all objects are removed in all tests!

**Comment by sgrieder** [comment]
To repair:
- test_EFA: line 303 (test factor analyses are performed correctly) does not hold
