### ISSUE TITLE
update documentations

### ISSUE THREAD

**Issue by mdsteiner** [mdsteiner/EFAtools#8]
make sure documentations are correct

**Comment by sgrieder** [comment]
EFAdiff.so in package

**Comment by sgrieder** [comment]
To do for (delete function name if documentation is updated for all but citations, these are listed elsewhere):
- compare
- EFA
- EFAtools-package
- helper
- HULL
- OMEGA_helper
- OMEGA
- PAF
- ULS
- ML
- PARALLEL
- plot.HULL.R
- plot.PARALLEL.R
- population_models_doc.R -> MARKUS
- print.ULS.R
- print.ML.R
- print.COMMUNALITIES.R
- print.COMPARE.R
- print.EIGEN.R
- print.HULL.R
- print.KMO.R
- print.LOADINGS.R
- print.PAF.R
- print.PARALLEL.R
- print.PROMAX.R
- print.SL.R
- print.SLLOADINGS.R
- print.VARIMAX.R
- PROMAX.R
- RcppExports.R
- SL.R
- utils-pipe.R
- VARIMAX_SPSS.R -> MARKUS, löschen?
- VARIMAX.R

**Comment by sgrieder** [comment]
KMO and BARTLETT -> refer to Revelles functions for credit

**Comment by sgrieder** [comment]
check that formula are displayed accurately (KMO and BARTLETT)
